rsh/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
  url(r'^(?P<gid>\d+)/$', 'rsh.views.task_list', name="task_list"),
  url(r'^(?P<gid>\d+)/task/(?P<tid>\d+)/$', 'rsh.views.newtask', name="task"),
  url(r'^(?P<gid>\d+)/newtask/$', 'rsh.views.newtask', name="newtask"),
  url(r'^(?P<gid>\d+)/task_management/$', 'rsh.views.task_management', name="task_management"),
  url(r'^(?P<gid>\d+)/sign_task/(?P<tid>\d+)/$', 'rsh.views.sign_task', name="sign_task"),
)

urls.py
# coding: utf-8
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
  url(r'^$', 'main.views.program_list', name="program_list"),  
  (r'^pin/', include('sbh.pin.urls')),
  (r'^rsh/', include('sbh.rsh.urls')),
  (r'^accounts/$', login), # {'template_name': 'pin/login.html'}),
  (r'^accounts/login/$', login), # {'template_name': 'pin/login.html'}),
  (r'^accounts/logout/$', logout), #, {'template_name': 'pin/logout.html'}),

  # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
  # to INSTALLED_APPS to enable admin documentation:
  # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

  (r'^admin/(.*)', admin.site.root),
)

# Needed on django test server, but not on apache
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),
    )

rsh/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from sbh.main.models import GasStation

class Task(models.Model):
  name = models.CharField(max_length=100)
  station = models.ForeignKey(GasStation)
  time = models.TimeField('Time')
  periodstart = models.DateField('Date', null=True, blank=True)
  periodend = models.DateField('Date', null=True, blank=True)
  type = models.IntegerField()
  repeat = models.IntegerField(null=True, blank=True)
  dayofmonth = models.IntegerField(null=True, blank=True)
  days = models.CharField(max_length=32, null=True, blank=True)

  def __unicode__(self):
    return self.name

class DayTask(models.Model):
  name = models.CharField(max_length=100)
  station = models.ForeignKey(GasStation)
  time = models.TimeField('Time')
  date = models.DateField('Date')
  signature = models.ForeignKey(User, null=True, blank=True)
  timestamp = models.DateTimeField('Signature Time', null=True, blank=True)

  def __unicode__(self):
    return self.name

rsh/forms.py
# coding: utf-8
from django import forms
from django.utils.safestring import mark_safe
from sbh.rsh.models import Task, DayTask
from django.forms.extras.widgets import SelectDateWidget

def _choosen(value):
  if value == '0':
    return None
  else:
    return '1'

class NewTaskForm(forms.Form):

  taskTypes = [(1,"Dag"), (2,"Vecka"), (3,"Månad")]
  taskHour = [(0,"00:00"), (1,"01:00"), (2,"02:00"), (3,"03:00"), (4,"04:00"),
              (5,"05:00"), (6,"06:00"), (7,"07:00"), (8,"08:00"), (9,"09:00"),
              (10,"10:00"), (11,"11:00"), (12,"12:00"), (13,"13:00"), (14,"14:00"),
              (15,"15:00"), (16,"16:00"), (17,"17:00"), (18,"18:00"), (19,"19:00"),
              (20,"20:00"), (21,"21:00"), (22,"22:00"), (23,"23:00")]

  def __init__(self, gid, tid=0, *args, **kwargs):
    super(NewTaskForm, self).__init__(*args, **kwargs)

    task = None
    if tid != 0:
      try:
        task = Task.objects.get(id = tid)
      except Task.DoesNotExist:
        pass

    if task:
      self.fields['name'] = forms.CharField(label=u"Aktivitet", initial=task.name)
      self.fields['time'] = forms.ChoiceField(label=u"Tid", choices = self.taskHour,
                                            initial=task.time.hour)
      self.fields['periodstart'] = forms.DateField(label=u"Period Början", required=False,
                                            initial=task.periodstart)
      self.fields['periodend'] = forms.DateField(label=u"Period Slut", required=False,
                                            initial=task.periodend)
      self.fields['type'] = forms.ChoiceField(label=u"Typ", choices = self.taskTypes,
                                            #widget=forms.RadioSelect(),
                                            initial=task.type)
      self.fields['dayofmonth'] = forms.IntegerField(label=u"Dag i månad", required=False,
                                min_value=1, max_value=31, initial=task.dayofmonth)
      self.fields['repeat'] = forms.IntegerField(label=u"Upprepa var", required=False,
                            min_value=0, initial=task.repeat)
    else:
      self.fields['name'] = forms.CharField(label=u"Aktivitet")
      self.fields['time'] = forms.ChoiceField(label=u"Tid", choices = self.taskHour)
      self.fields['periodstart'] = forms.DateField(label=u"Period Början", required=False)
      self.fields['periodend'] = forms.DateField(label=u"Period Slut", required=False)
      self.fields['type'] = forms.ChoiceField(label=u"Typ", choices = self.taskTypes,
                                                 #widget=forms.RadioSelect(),
                                                 initial=0)
      self.fields['dayofmonth'] = forms.IntegerField(label=u"Dag i månad", required=False,
                                min_value=1, max_value=31)
      self.fields['repeat'] = forms.IntegerField(label=u"Återupprepning", required=False,
                            min_value=0)

    if task and task.type == 2:
      self.fields['daymon'] = forms.BooleanField(label=u"Måndag", required=False,
                                            initial=_choosen(task.days[0]))
      self.fields['daytue'] = forms.BooleanField(label=u"Tisdag", required=False,
                                            initial=_choosen(task.days[1]))
      self.fields['daywed'] = forms.BooleanField(label=u"Onsdag", required=False,
                                            initial=_choosen(task.days[2]))
      self.fields['daythr'] = forms.BooleanField(label=u"Torsdag", required=False,
                                            initial=_choosen(task.days[3]))
      self.fields['dayfri'] = forms.BooleanField(label=u"Fredag", required=False,
                                            initial=_choosen(task.days[4]))
      self.fields['daysat'] = forms.BooleanField(label=u"Lördag", required=False,
                                            initial=_choosen(task.days[5]))
      self.fields['daysun'] = forms.BooleanField(label=u"Söndag", required=False,
                                            initial=_choosen(task.days[6]))
    else:
      self.fields['daymon'] = forms.BooleanField(label=u"Måndag", required=False)
      self.fields['daytue'] = forms.BooleanField(label=u"Tisdag", required=False)
      self.fields['daywed'] = forms.BooleanField(label=u"Onsdag", required=False)
      self.fields['daythr'] = forms.BooleanField(label=u"Torsdag", required=False)
      self.fields['dayfri'] = forms.BooleanField(label=u"Fredag", required=False)
      self.fields['daysat'] = forms.BooleanField(label=u"Lördag", required=False)
      self.fields['daysun'] = forms.BooleanField(label=u"Söndag", required=False)

rsh/views.py
# coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from sbh.rsh.forms import NewTaskForm
from sbh.rsh.models import Task, DayTask
from sbh.main.models import GasStation, UserAuth
from datetime import datetime, timedelta, date

@login_required()
def task_list(request, gid):
  gid = int(gid)
  try: # Check user level for app
    uauth = UserAuth.objects.get(user = request.user, station = gid, app = 2)
  except UserAuth.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))
  if uauth.level < 1:
    return HttpResponseRedirect(reverse('program_list'))
  elif uauth.level > 1:
    adm = True
  else:
    adm = False

  today = date.today()
  # Try to get todays tasks
  task_list = DayTask.objects.filter(station = gid, date = today).order_by('time')
  if len(task_list) == 0: # No tasks today, try to create a list
    tasks = Task.objects.filter(Q(station = gid),
              Q(periodstart__isnull=True) | Q(periodstart__lte=today),
		      Q(periodend__isnull=True) | Q(periodend__gte=today))
    #raise Oskar
    # Weekday
    task_list =  []
    for task in tasks.filter(type = 1):
      # If repeat; get timedelta with the task start date and do modulus
      if task.repeat is None or ((today - task.periodstart).days % task.repeat == 0):
        task_list.append(task)
    # Day of week
    for task in tasks.filter(type = 2):
      try:
        # If repeat; get timedelta between first days of the weeks and do modulus
        if task.days[today.weekday()] != '0' and (task.repeat is None or
            ((today - task.periodstart - timedelta(today.weekday() -
              task.periodstart.weekday())).days / 7) % task.repeat == 0):
          task_list.append(task)
      except IndexError:
        pass
    # Day of month
    for task in tasks.filter(type = 3):
      try:
        # If repeat; calculate number of months between dates and do modulus
        if task.dayofmonth == today.day and (task.repeat is None or 
            ((today.year - task.periodstart.year) * 12 +
             today.month - task.periodstart.month) % task.repeat == 0):
          task_list.append(task)
      except IndexError:
        pass

    # Create DayTasks for today
    for task in task_list:
      dt = DayTask(station=task.station, name=task.name, date=today, time=task.time)
      dt.save()
    try:
      task_list = DayTask.objects.filter(station = gid, date = today).order_by('time')
    except Task.DoesNotExist:	# No tasks today
      task_list = None

  
  c = RequestContext(request, {'object_list': task_list, 'gid': gid, 'adm': adm})
  return render_to_response('rsh/task_list.html', c)

# Also used to edit a task (tid != 0)
@login_required()
def newtask(request, gid, tid=0):
  gid = int(gid)
  tid = int(tid)
  try: # Check user level for app
    uauth = UserAuth.objects.get(user = request.user, station = gid, app = 2)
  except UserAuth.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))
  if uauth.level < 2:
    return HttpResponseRedirect(reverse('program_list'))

  try:  # Make sure Gas Station exists, if not redirect 
    gs = GasStation.objects.get(id = gid)
  except GasStation.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))

  if request.method == 'POST':
    form = NewTaskForm(gid, tid, data=request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      try:
        type = int(cd['type'])
        repeat = int(cd['repeat'])
        days = None
        dayofm = None
        if type == 2:
          days = "%d%d%d%d%d%d%d" % (cd['daymon'], cd['daytue'],
                      cd['daywed'], cd['daythr'], cd['dayfri'], cd['daysat'],
                      cd['daysun'])
        elif type == 3:
          dayofm = int(cd ['dayofmonth'])
      except ValueError:
        pass
      else:
        try:
          task = Task.objects.get(station=gid, id=tid)
          task.name = cd['name']
          task.time = u"%s:00" % cd['time']
          task.periodstart = cd['periodstart']
          task.periodend = cd['periodend']
          task.type = type
          task.repeat = repeat
          task.days = days
          task.dayofmonth = dayofm
        except Task.DoesNotExist:
          task = Task(station=gs, name = cd['name'], time = u"%s:00" % cd['time'],
                      periodstart = cd['periodstart'], periodend = cd['periodend'],
                      type = type, repeat = repeat, dayofmonth = dayofm, days = days)
        task.save()
        return HttpResponseRedirect(reverse('task_management', args=[gid]))
  else:
    form = NewTaskForm(gid, tid)

  initialtype = form.fields['type'].initial - 1 # Ugly but found no better way
  c = RequestContext(request, {'form': form, 'gid': gid, 'initialtype':initialtype})
  return render_to_response('rsh/newtask.html', c)

@login_required()
def task_management(request, gid):
  gid = int(gid)
  try: # Check user level for app
    uauth = UserAuth.objects.get(user = request.user, station = gid, app = 2)
  except UserAuth.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))
  if uauth.level < 2:
    return HttpResponseRedirect(reverse('program_list'))
  try:	# Make sure tasks exist, if not redirect
    task_list = Task.objects.filter(station = gid).order_by('name')
  except Task.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))

  c = RequestContext(request, {'object_list': task_list, 'gid': gid})
  
  return render_to_response('rsh/task_management.html', c)

@login_required()
def sign_task(request, gid, tid):
  gid = int(gid)
  tid = int(tid)
  try: # Check user level for app
    uauth = UserAuth.objects.get(user = request.user, station = gid, app = 2)
  except UserAuth.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))
  if uauth.level < 1:
    return HttpResponseRedirect(reverse('program_list'))

  try:
    task = DayTask.objects.get(id = tid, station = gid)
  except DayTask.DoesNotExist:
    return HttpResponseRedirect(reverse('program_list'))
  
  task.signature = request.user
  task.timestamp = datetime.now()
  task.save()

  return HttpResponseRedirect(reverse('task_list', args=[gid]))

templates/rsh/base.html
{% extends "base.html" %}

{% block header %}<h1>Aktiviteter</h1>{% endblock %}

{% block breadcrumb %}{{ block.super}}<li class="menu"><a class="menu" href="{% url task_list gid %}">&raquo; RSH</a></li>{% endblock %}

{% block footer %}
  <hr>
  <p>En Applikation från Efficient</p>
{% endblock %}

templates/rsh/newtask.html
{% extends "rsh/base.html" %}

{% block extra_head %}
<script type="text/javascript">
  $(document).ready(function() {
    $("#id_periodstart").datepicker({showOn: 'both', buttonImage:'/site_media/images/calendar.gif', buttonImageOnly: true, dateFormat: 'yy-mm-dd'});
    $("#id_periodend").datepicker({showOn: 'both', buttonImage: '/site_media/images/calendar.gif', buttonImageOnly: true, dateFormat: 'yy-mm-dd'});
    $("#tabs").tabs({
      select: function(event, ui) { 
        var selected = ui.index;  // Index of selected tab
        $("#id_type").val(selected + 1);
        if (selected==0) { $("#repeat_lbl").text("dag"); }
        else if (selected==1) { $("#repeat_lbl").text("vecka"); }
        else { $("#repeat_lbl").text("månad"); }
      }
    });
    $("#tabs").tabs('select', {{ initialtype  }});
    $("#typeselector").hide();
  });
</script>
{% endblock %}

{% block breadcrumb %}
  {{ block.super}}
  <li class="menu"><a class="menu" href="{% url task_management gid %}">&raquo; Administrera Aktiviteter</a></li>
  <li class="menu"><a class="menu" href="#">&raquo; Ny aktivitet</a></li>
{% endblock %}

{% block content %}

  {% if form.errors %}
    <div class="fg-message ui-state-error fg-message-icon-left ui-corner-all">
      <span class="ui-icon ui-icon-alert"></span>Det finns fel i formuläret
    </div> 
  {% endif %}

  <form action="" method="post">
    <table>
      <tr><td>{{ form.name.label_tag }}</td><td colspan=4>{{ form.name }}</td><td colspan=2>{{ form.name.errors}}</td></tr>
      <tr><td>{{ form.time.label_tag }}</td><td colspan=4>{{ form.time.as_widget }}</td><td colspan=2>{{ form.time.errors}}</td></tr>
      <tr><td>{{ form.periodstart.label_tag }}</td><td colspan=4>{{ form.periodstart }}</td><td colspan=2>{{ form.periodstart.errors}}</td></tr>
      <tr><td>{{ form.periodend.label_tag }}</td><td colspan=4>{{ form.periodend }}</td><td colspan=2>{{ form.periodend.errors}}</td></tr>
      <tr id="typeselector"><td>{{ form.type.label_tag }}</td><td colspan=4>{{ form.type }}</td><td colspan=2>{{ form.type.errors}}</td></tr>
    </table>
    <div class="ui-tabs ui-widget ui-widget-content ui-corner-all" id="tabs">
      <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
      <li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active"><a href="#tabs-1">Dag</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#tabs-2">Vecka</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#tabs-3">Månad</a></li>
      </ul>
      <div class="ui-tabs-panel ui-widget-content ui-corner-bottom" id="tabs-1">
        <p>Det finns inga speciella parametrar för dagliga aktiviteter</p>     
      </div>
      <div class="ui-tabs-panel ui-widget-content ui-corner-bottom" id="tabs-2">
        <ul class="menu">
        <li class="menu">{{ form.daymon.label_tag }}{{ form.daymon }}</li>
        <li class="menu">{{ form.daytue.label_tag }}{{ form.daytue }}</li>
        <li class="menu">{{ form.daywed.label_tag }}{{ form.daywed }}</li>
        <li class="menu">{{ form.daythr.label_tag }}{{ form.daythr }}</li>
        <li class="menu">{{ form.dayfri.label_tag }}{{ form.dayfri }}</li>
        <li class="menu">{{ form.daysat.label_tag }}{{ form.daysat }}</li>
        <li class="menu">{{ form.daysun.label_tag }}{{ form.daysun }}</li>
        </ul>
      </div>
      <div class="ui-tabs-panel ui-widget-content ui-corner-bottom" id="tabs-3">
        {{ form.dayofmonth.label_tag }} {{ form.dayofmonth }} {{ form.dayofmonth.errors}}
      </div>
    </div>
    {{ form.repeat.label_tag }} {{ form.repeat }}:e <label id="repeat_lbl">dag</label> {{ form.repeat.errors}}<br />
    <input type="submit" value="Spara">
  </form>
{% endblock %}

templates/rsh/task_list.html
{% extends "rsh/base.html" %}

{% block content %}

{% if object_list %}
  <table class="formtable">
  <tr class="ui-widget-header"><td>Tid</td><td>Aktivitet</td><td></td></tr>
  {% for object in object_list %}
    {% if object.signature %}
      <tr><td>{{ object.time }}</td><td>{{ object.name }}</td><td>{{ object.signature }}</td></tr>
    {% else %}
      <tr><td>{{ object.time }}</td><td>{{ object.name }}</td><td><a href="{% url sign_task gid object.id %}">Signera</a></td></tr>
    {% endif %}
  {% endfor %}
  </table>
{% else %}
  <div class="ui-widget center300">
    <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
    <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>Det finns inga aktiviteter idag</p>
    </div>
  </div>
{% endif %}

{% if adm %}
  <div class="padded">
  <a href="{% url task_management gid %}" class="fg-button ui-state-default ui-corner-all">Administrera Aktiviteter</a>
  </div>
{% endif %}

{% endblock %}

templates/rsh/task_management.html
{% extends "rsh/base.html" %}

{% block breadcrumb %}{{ block.super}}
<li class="menu"><a class="menu" href="#">&raquo; Administrera Aktiviteter</a></li>
{% endblock %}
{% block content %}

{% if object_list %}
  <table class="formtable">
  <tr class="ui-widget-header"><th>Tid</th><th>Aktivitet</th><th></th></tr>
  {% for object in object_list %}
    <tr><td class="ui-widget-content">{{ object.time }}</td><td class="ui-widget-content">{{ object.name }}</td><td class="ui-widget-content"><a href="{% url task gid object.id %}">Redigera</a></td></tr>
  {% endfor %}
  </table>
{% else %}
  <div class="ui-widget center300">
    <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
    <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>Det finns inga aktiviteter</p>
    </div>
  </div>
{% endif %}
<div class="padded">
  <a class="fg-button ui-state-default ui-corner-all" href="{% url newtask gid %}">Ny Aktivitet</a>
</div>
{% endblock %}